# -*- encoding: utf-8 -*-
{
    "name": "FEOS: Workflow for Asset Management",
    "version": "1.0",
    "depends": ["feosco_account_asset"],
    "author": "Feosco",
    "description": """Workflow for Asset Management""",
    "website": "http://www.feosco.com",
    "category": "Feosco",
    "init_xml": [],
    "demo_xml": [],
    'test': [],
    "data": [
		'data/sequence.xml',
		'security/ir.model.access.csv',
		'security/domain.xml',
		'view/asset_contract.xml',
		'view/asset_contract_line.xml',
		'view/asset_request.xml',
		'view/asset_request_line.xml',
		'view/asset_stock.xml',
		'view/asset_contract_role.xml',
		'view/invoice.xml',
		'view/product.xml',
		'view/main_menu.xml',
    ],
    "auto_install": False,
    "installable": True,
    "application": False,
}

